### PR TITLE
Revert #1280

### LINKED ISSUE #1298: Flakey test
The test: https://github.com/asdf-format/asdf/blob/a2d2c4723ab8a8cdc0eb3f87fb913a80d728e5b9/asdf/tests/test_array_blocks.py#L834-L851

introduced in #1280 seems to be intermittently flaky for reasons I cannot explain. I see failures in the CI

See:

- https://github.com/asdf-format/asdf/actions/runs/3903417026/jobs/6667758950
- https://github.com/asdf-format/asdf/actions/runs/3880159122/jobs/6618149855

But when simply re-running the CI:

- https://github.com/asdf-format/asdf/actions/runs/3903417026/jobs/6668675088
- https://github.com/asdf-format/asdf/actions/runs/3885577317/jobs/6629628167 (note that I did some debugging before making an identical re-run)

The CI passes. I don't think this is related to the changes PR #1293, though all the failures are in CI for those changes. I think the issue is more that #1293 happens to have run the CI many times.

### PR DESCRIPTION
**Pull request by braingram**
Fixes #1298

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
Let's revert and open a new issue to track adding the feature in #1280. #1280 seemed reasonable, so I would like to figure out and document why this is flakey. It would be great if we could figure out a better solution.

**Comment by braingram** [comment]
Thanks.

I'll open an issue to track re-adding #1280

The CI failure might be related to numpy development dropping 3.8 for the 1.25 release. I will open a separate asdf issue for that.

**Review by zacharyburnett — APPROVED** [review]
LGTM

**Comment by WilliamJamieson** [comment]
> The CI failure might be related to numpy development dropping 3.8 for the 1.25 release. I will open a separate asdf issue for that.

Good to know. It will be nice to drop 3.8 support. Maybe we should ahead of the LTS version for ASDF 2 discussed in #1323.

**Review by WilliamJamieson — APPROVED** [review]
LGTM.

We should drop dev support and pin numpy on Python 3.8. (Separate issue)

**Pull request merged**
