### PR TITLE
fix saving fortran ndarray issue #1205

### PR DESCRIPTION
**Pull request by braingram**
per eslavich the contiguous array check should check for both f and c order array so modified flags.contiguous to flags.forc

modified ndarray test_fortran_order test to verify fortran ordered on 'roundtrip' write then read

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
Does this fix the extra source being written to the file and add the `stride` to the file?

**Comment by braingram** [comment]
Both those issues appear to be fixed.

Running the test script from issue #1205 produces the following output:
```bash
Original farray:
 [[11 12 13]
 [21 22 23]]
Recovered farray:
 [[11 12 13]
 [21 22 23]]
Original carray:
 [[11 12 13]
 [21 22 23]]
Recovered carray:
 [[11 12 13]
 [21 22 23]]
```
and the following strides.asdf (blocks removed for readability but including the index to show the 2 blocks)
```yaml
#ASDF 1.0.0
#ASDF_STANDARD 1.5.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
asdf_library: !core/software-1.0.0 {author: The ASDF Developers, homepage: 'http://github.com/asdf-format/asdf',
  name: asdf, version: 2.13.1.dev54+g271fe197.d20221006}
history:
  extensions:
  - !core/extension_metadata-1.0.0
    extension_class: asdf.extension.BuiltinExtension
    software: !core/software-1.0.0 {name: asdf, version: 2.13.1.dev54+g271fe197.d20221006}
carray: !core/ndarray-1.0.0
  source: 1
  datatype: int64
  byteorder: little
  shape: [2, 3]
farray: !core/ndarray-1.0.0
  source: 0
  datatype: int64
  byteorder: little
  shape: [2, 3]
  strides: [8, 16]
...
#ASDF BLOCK INDEX
%YAML 1.1
---
- 674
- 776
...
```
This also appears to fix the related issue where validating a tree with a f order array results in allocation of a new unused block (each time validate is called).

**Comment by WilliamJamieson** [comment]
We should add regression tests for this.

**Comment by braingram** [comment]
Agreed! Is there a specific place for these and something you would recommend?

I modified [test_fortran_order](https://github.com/braingram/asdf/blob/bug/fortran_ndarray/asdf/tags/core/tests/test_ndarray.py#L803) in commit bf2c14479 to check for fortran ordering after 'round tripping' the data to disk. This wasn't being tested before and after adding the check the test failed until flags.forc was used.

**Comment by WilliamJamieson** [comment]
One should be able to test that `strides` are being written as part of the `ndarray` tests: https://github.com/asdf-format/asdf/blob/master/asdf/tags/core/tests/test_ndarray.py. I'm not sure where testing that only one block is created should go.

**Review by WilliamJamieson — APPROVED** [review]

**Pull request merged**
