### PR TITLE
MNT: Replace distutils with packaging

### PR DESCRIPTION
**Pull request by pllim**
`distutils` is deprecated. cc @eslavich

### CODE REVIEW

**Comment by pllim** [comment]
Hmm I don't understand the error.

`error: package directory 'asdf-standard/resources' does not exist`

**Comment by eslavich** [comment]
> error: package directory 'asdf-standard/resources' does not exist

This is just the submodule giving us grief again... @WilliamJamieson has a plan to get rid of it and replace with a normal Python dependency, hopefully soon.

**Comment by pllim** [comment]
As discussed offline, @WilliamJamieson will take over this PR. I think the compatibility test needs to be rewritten because `packaging.version.Version` is not a drop-in replacement for `distutils.StrictVersion`. Care needs to be given to return data type (unless backward compatibility for this module is not a problem) and comparison logic.

**Comment by pllim** [comment]
Ah, I was sooo close. 😆 

Thanks for wrapping this up, @WilliamJamieson !

**Pull request merged**
