### PR TITLE
Unpin Pytest < 6

### PR DESCRIPTION
**Pull request by bnavigator**
pytest-doctestplus has been compatible with pytest 6 since version 0.8

As Pytest 5 is not compatible with Python 3.10, this is a blocker.

### CODE REVIEW

**Comment by bnavigator** [comment]
Oh wow. That's quite some fallout with the changed importing mechanism in Pytest 6.

**Comment by eslavich** [comment]
I'm not sure, but I think adding this to tox.ini under `[testenv]` will help:

```
usedevelop= true
```

**Comment by bnavigator** [comment]
> I'm not sure, but I think adding this to tox.ini under `[testenv]` will help:
> 
> ```
> usedevelop= true
> ```

Correct! Thank you!

**Comment by eslavich** [comment]
Hooray!  The `Twine` and `Test Against Installed Packaged` jobs should be overridden with usedevelop= false again.  I don't know what's going on with the "Warnings Treated as Exceptions` job, but I can investigate that in the morning if you don't beat me to it.

**Comment by eslavich** [comment]
#1037 refers to updating these to use 3.10:

https://github.com/asdf-format/asdf/blob/master/.github/workflows/ci.yml#L120
https://github.com/asdf-format/asdf/blob/master/tox.ini#L41

**Review by eslavich — APPROVED** [review]
🎉

**Comment by eslavich** [comment]
@bnavigator do you need a release of these fixes?

**Comment by bnavigator** [comment]
No, I already worked around it in the rpm package. After all this is only testing, nothing facing the user.

**Pull request merged**
