### PR TITLE
Add note to contributing guide about backport labels

### PR DESCRIPTION
**Pull request by WilliamJamieson**
Document the backport system.

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
Try close/reopen

**Review by braingram — APPROVED** [review]

**Comment by WilliamJamieson** [comment]
@MeeseeksDev backport

**Comment by WilliamJamieson** [comment]
@MeeseeksDev backport to 2.15.x

**Comment by WilliamJamieson** [comment]
Oops wrong PR to try forcing the backport on

**Pull request merged**
