### PR TITLE
Bugfixes for sphinx

### LINKED ISSUE #1110: Invalid test.asdf files in the RTD documenation
Many (most? all?) of the result test.asdf files shown in the readthedocs.io (RTD) documentation are not valid ASDF files using asdf 2.10.1 .

The "Hello World" example at  
https://asdf.readthedocs.io/en/stable/asdf/overview.html#hello-world  
```
from asdf import AsdfFile

# Make the tree structure, and create a AsdfFile from it.
tree = {'hello': 'world'}
ff = AsdfFile(tree)
ff.write_to("test.asdf")

# You can also make the AsdfFile first, and modify its tree directly:
ff = AsdfFile()
ff.tree['hello'] = 'world'
ff.write_to("test.asdf")
```
produces the following test.asdf file 
```
#ASDF 1.0.0
#ASDF_STANDARD 1.5.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
asdf_library: !core/software-1.0.0 {author: The ASDF Developers, homepage: 'http://github.com/asdf-format/asdf',
  name: asdf, version: 2.10.1}
history:
  extensions:
  - !core/extension_metadata-1.0.0
    extension_class: asdf.extension.BuiltinExtension
    software: !core/software-1.0.0 {name: asdf, version: 2.10.1}
hello: world
...
```
using asdf 2.10.1 and Python 3.9.7.

The RTD documentation gives this result
```
test.asdfb'#ASDF' 1.5.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
asdf_library: !core/software-1.0.0 {author: Space Telescope Science Institute, homepage: 'http://github.com/spacetelescope/asdf',
  name: asdf, version: 2.7.5}
history:
  extensions:
  - !core/extension_metadata-1.0.0
    extension_class: asdf.extension.BuiltinExtension
    software: !core/software-1.0.0 {name: asdf, version: 2.7.5}
hello: world
...
```

The asdftool issues this error  
ValueError: Input object does not appear to be an ASDF file or a FITS with ASDF extension  
with the current RTD version of test.asdf.

This is not surprising given that the current RTD version of test.asdf starts with this line:  
```test.asdfb'#ASDF' 1.5.0```

### PR DESCRIPTION
**Pull request by WilliamJamieson**
Bug fixes for the documentation.

Fixes #1110

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
@perrygreenfield what do you think of the
```
FILENAME: test.asdf
=========

```
portion of the asdf section [here](https://asdf--1111.org.readthedocs.build/en/1111/asdf/overview.html#hello-world) in the documents? This will be repeated everywhere where the asdf file content inclusion is automatically included.

I am debating between something similar to this and dropping the filename/title from those blocks all together.

**Comment by WilliamJamieson** [comment]
@KenMighell please feel free to comment on the changes to the asdf file content inclusion changes as well.

**Comment by perrygreenfield** [comment]
The construction

```
FILENAME: test.asdf
=========
```

Appears to be a good solution to me.

**Comment by WilliamJamieson** [comment]
@KenMighell found another formatting issue with how the asdf sphinx directive displays the binary blocks. One can see the fixed version here: https://asdf--1111.org.readthedocs.build/en/1111/asdf/arrays.html?highlight=block vs the broken version here: https://asdf.readthedocs.io/en/stable/asdf/arrays.html?highlight=block.

**Comment by WilliamJamieson** [comment]
Windows failure is related to issue pytest-dev/pytest#9765 and appears to have persisted to pytest 7.1.1.

**Comment by KenMighell** [comment]
I found an old example (```https://asdf.readthedocs.io/en/1.2.1/asdf/examples.html```) that nicely displayed an ASDF result file with raw binary in a box with 3 sections: (1) the first section is human-readable YAML  code from the start of the ASDF file, (2) the second section is a (human readable) summary of the content of the raw binary block in the ASDF file, and (3) the last section is human-readable YAML code near the end of the ASDF file.   The name of the ASDF is shown at the top as white-bold text in a green bar.

image

**Comment by pllim** [comment]
At its current state, maybe it is less confusing to omit the filename altogether.

**Comment by WilliamJamieson** [comment]
@KenMighell, your point about the old documentation is valid. However, none of the directly relevant sphinx code has changed in any meaningful way (aside from the tweaks of this PR) between version 1.2.1 and the current 2.11.0 version. This likely means that the display difference is the result of a difference in sphinx, the sphinx theme, or sphinx configuration over the intervening time between 1.2.1 and 2.11.0.

**Pull request merged**
