### PR TITLE
Remove 'name' and 'version' attributes from NDArrayType instances

### LINKED ISSUE #1015: NDArrayType attributes when reading from tree
The `NDArrayType` is a bit different from other asdf types in that the `from_tree` returns an instance of the `NDArrayType` (instead of the mapped python types)

This also means that you can access the classattributes `.name='core/ndarray'` and `.version='1.0.0'` from any instance. From my understanding, these attributes are only used for generating the appropriate tag mapping for the asdf extension?

Unfortunately this can have unexpected results when using the loaded array with other libraries that check for these attributes on class creation, see here https://github.com/BAMWelDX/weldx/issues/110

In the attributes are not needed on the instances returned by `from_tree` by asdf after creation, can they be set to `None` so that other code is less likely to pick them up? see https://github.com/CagtayFabry/asdf/commit/603b01664eda3d7f7305d184a859d719b8aad50c

### PR DESCRIPTION
**Pull request by eslavich**
@CagtayFabry what do you think about this alternative fix?  My concern with #1016 is that we won't catch all the cases where an NDArrayType is created.

Resolves #1015

### CODE REVIEW

**Comment by CagtayFabry** [comment]
> @CagtayFabry what do you think about this alternative fix? My concern with #1016 is that we won't catch all the cases where an NDArrayType is created.
> 
> Resolves #1015

this looks like a much cleaner solution, thanks!

**Comment by perrygreenfield** [comment]
Just to clarify, the idea here is to effectively remove these attributes from the class instances, but not the class itself (which the tag machinery would use)?

**Comment by eslavich** [comment]
> Just to clarify, the idea here is to effectively remove these attributes from the class instances, but not the class itself (which the tag machinery would use)?

Yes, just so!

**Review by perrygreenfield — APPROVED** [review]
LGTM

**Pull request merged**
