### PR TITLE
Add --ignore-query flag to asdftool diff

### PR DESCRIPTION
**Pull request by eslavich**
This adds a `--ignore-query` (or `-i`) flag to the asdftool diff command.  It accepts a JMESPath expression and ignores matching nodes when computing the diff.

### CODE REVIEW

**Review by jdavies-st — COMMENTED** [review]
Cool!  This is very simple, and I like it.

That said, it's not clear how to use it, so a couple simple examples in the docs and a docstring somewhere would be useful.

Also, I know `jmespath` calls these queries, but from a top-level `asdf` user standpoint, when using `asdftool`, it might be clearer to use:

```
$ asdftool diff --ignore=meta.date file1.asdf file2.asdf
$ asdftool diff --ignore="meta.[date, filename]" file1.asdf file2.asdf
```

as we are using it not so much as a query at the top level but as a filter, even though the string is a query.

**Review by nden — APPROVED** [review]
I agree with James' comments. `ignore` or `ignore_attrs` sounds better to me.
Other than that it looks good and works well.

**Comment by eslavich** [comment]
I changed the argument name to `--ignore`, added an epilogue with examples, and added a docstring.  Let me know if you think that's sufficient, documentation-wise.

**Review by jdavies-st — APPROVED** [review]
This looks good!

**Pull request merged**
