### PR TITLE
add upper pin to jsonschema

### PR DESCRIPTION
**Pull request by braingram**
jsonschema 4.18 will introduce changes that are incompatible with asdf. More details can be found in:
https://github.com/asdf-format/asdf/issues/1485

this commit adds an upper pin to jsoncschema and removes it from the devdeps testing

As described in the issue, adding a warning filter was insufficient to allow the devdeps jobs to pass.

An issue was created to track removing the pin:  https://github.com/asdf-format/asdf/issues/1486

### CODE REVIEW

**Review by WilliamJamieson — CHANGES_REQUESTED** [review]
I am normally against commenting things out instead of removing them.

In this case, I want it clearly documented why we have stopped the testing against jsonschema dev and why we have introduced an upper pin within the code itself. Otherwise, it becomes unclear when examining the code at first glance why these changes have been made and the intent for them to be temporary changes.

**Comment by braingram** [comment]
> Should an issue with `jsonschema` be opened about this? That clearly indicates the changes are not backwards compatible.

I am suspicious that something is up with the reference resolution in meta schemas but so far I've been unable to come up with a non-asdf minimal case that fails. Given the extensive use of non-public portions of jsonschema within asdf it's possible the changes did not introduce any public backwards incompatibility and the issues we're encountering are our own fault. I'd rather wait to open an issue until we can determine that jsonschema is at fault.

**Review by WilliamJamieson — APPROVED** [review]
Hopefully these changes will be temporary

**Comment by pllim** [comment]
I vaguely remember a maxversion pin of jsonschema in the past, and eventually that gave astropy problems when something else required a new jsonschema that asdf cannot use. So hopefully this won't stay forever. 🤞

**Comment by WilliamJamieson** [comment]
@meeseeksdev backport to 2.14.x

**Pull request merged**
