### PR TITLE
Enable CRDS for stdatamodels downstream

### PR DESCRIPTION
**Pull request by WilliamJamieson**
This should fix the downstream tests for stdatamodels.

### CODE REVIEW

**Review by zacharyburnett — APPROVED** [review]
LGTM

**Review by braingram — CHANGES_REQUESTED** [review]
This fails to fix the issue:
https://github.com/asdf-format/asdf/actions/runs/4105988581/jobs/7083632898#step:9:844

**Comment by zacharyburnett** [comment]
I have had success in using `/tmp/crds_cache` instead of `$HOME/crds_cache` in other workflows; perhaps we could set that in `ci.yml` and then use `pass_env: CRDS`

**Comment by WilliamJamieson** [comment]
I think this is superseded by #1349

**Pull request closed without merging**
