### PR TITLE
cache tox environments and make test workflows dependent upon linting 

### PR DESCRIPTION
**Pull request by zacharyburnett**
image

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
Some of the issues in this maybe resolved by rebasing this PR on master.

**Comment by zacharyburnett** [comment]
the tests appear to need `six`
```
/home/runner/work/asdf/asdf/asdf/entry_points.py:46: AsdfWarning: asdf_extensions plugin from package gwcs==0.17.1 failed to load:

  ModuleNotFoundError: No module named 'six'
```
https://github.com/asdf-format/asdf/runs/7027693077?check_suite_focus=true#step:7:1145

**Comment by WilliamJamieson** [comment]
> the tests appear to need `six`
> 
> ```
> /home/runner/work/asdf/asdf/asdf/entry_points.py:46: AsdfWarning: asdf_extensions plugin from package gwcs==0.17.1 failed to load:
> 
>   ModuleNotFoundError: No module named 'six'
> ```
> 
> https://github.com/asdf-format/asdf/runs/7027693077?check_suite_focus=true#step:7:1145

Maybe a similar change to the `tox` environment to add `six` should be used as was done in #1149.

Though why aren't we pulling the latest version of gwcs in this case? Another concerning thing is `asdf-astropy` is missing from the `pip freeze` which is why there are so many warnings (I see it in the current CI jobs' `pip freeze`). Is it possible that this is somehow interfering with the correct resolution of the dependencies?

**Comment by zacharyburnett** [comment]
it looks like the dependency resolution is having issues when installing `asdf-standard` from source
```
INFO: pip is looking at multiple versions of pytest-sugar to determine which version is compatible with other requirements. This could take a while.
```
https://github.com/asdf-format/asdf/runs/7133915672?check_suite_focus=true#step:7:171

**Pull request closed without merging**
