### PR TITLE
Consolidate toxenvs

### PR DESCRIPTION
**Pull request by zacharyburnett**
consolidates toxenvs to use common keywords and reduce configuration complexity, and updates keywords to Tox 4 snake case versions

### CODE REVIEW

**Comment by zacharyburnett** [comment]
@WilliamJamieson do you think this needs a change log entry?

**Comment by WilliamJamieson** [comment]
> @WilliamJamieson do you think this needs a change log entry?

This does not affect user facing code, it only affects the CI. Therefore it should not have a changelog entry.

**Comment by braingram** [comment]
It looks like something in these changes broke the coverage measurements:
https://github.com/asdf-format/asdf/actions/runs/4224891428/jobs/7336443630#step:9:103
https://github.com/asdf-format/asdf/pull/1396/checks?check_run_id=11469869479

**Comment by WilliamJamieson** [comment]
Can this branch be rebased?

**Review by WilliamJamieson — APPROVED** [review]

**Pull request merged**
